# Generated by Django 5.0.3 on 2024-06-19 16:07

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('msisdn', models.CharField(max_length=50)),
                ('accountholderstatus', models.CharField(max_length=50)),
                ('profilename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DepositFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankcode', models.CharField(default=37, max_length=30)),
                ('accountnumber', models.CharField(blank=True, default='20680300000', max_length=15, null=True)),
                ('amount', models.FloatField(max_length=15)),
                ('receiver', models.CharField(max_length=35)),
                ('transactiontimestamp', models.DateTimeField(default='2024-06-19T19:07:31')),
                ('currency', models.CharField(default='UGX', max_length=5)),
                ('banktransactionid', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=50)),
                ('receiverfirstname', models.CharField(max_length=50)),
                ('receiversurname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('trx_batchid', models.CharField(max_length=50)),
                ('trx_serialid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EcwGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Xsignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_signature', models.TextField(blank=True, null=True)),
                ('paymentinstructionid', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='EcwUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('needs_password_change', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecw.branch')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecw.ecwgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInstructionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentinstructionid', models.CharField(max_length=20)),
                ('receiverbankcode', models.CharField(max_length=20)),
                ('receiveraccountnumber', models.CharField(max_length=20)),
                ('receiverfirstname', models.CharField(max_length=50)),
                ('receiversurname', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('transmissioncounter', models.CharField(max_length=255, null=True)),
                ('transactionid', models.CharField(max_length=255, null=True)),
                ('amount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecw.amount')),
                ('transactiontimestamp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecw.transactiontimestamp')),
            ],
        ),
    ]
