# Generated by Django 4.2.13 on 2024-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0002_alter_applogs_logtimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-06-25T17:36:45'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='bankcode',
            field=models.CharField(default='37', max_length=30),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-25T17:36:45'),
        ),
    ]
