# Generated by Django 5.0.3 on 2024-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0002_alter_depositfunds_transactiontimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-20T08:40:23'),
        ),
    ]
