# Generated by Django 4.2.13 on 2024-06-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0003_alter_depositfunds_transactiontimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='banktransactionid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='bookingtimestamp',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='random_challenge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='response_status',
            field=models.CharField(blank=True, default='PENDING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-20T12:46:23'),
        ),
    ]
