# Generated by Django 4.2.13 on 2024-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0003_alter_applogs_logtimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-06-28T14:47:12'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-28T14:47:12'),
        ),
        migrations.AlterField(
            model_name='paymentinstructionrequest',
            name='paymentinstructionid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
