# Generated by Django 4.2.13 on 2024-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0004_paymentinstructionrequest_banktransactionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-20T16:16:54'),
        ),
        migrations.AlterField(
            model_name='paymentinstructionrequest',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
