# Generated by Django 4.2.13 on 2024-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0005_alter_applogs_logtimestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstructionrequest',
            name='trx_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-06-28T20:42:10'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-28T20:42:10'),
        ),
    ]
