# Generated by Django 4.2.13 on 2024-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0005_alter_depositfunds_transactiontimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-20T16:24:25'),
        ),
        migrations.AlterField(
            model_name='paymentinstructionrequest',
            name='receiverfirstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstructionrequest',
            name='receiversurname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
