# Generated by Django 4.2.13 on 2024-07-01 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0006_paymentinstructionrequest_trx_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositfunds',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositfunds',
            name='trx_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-07-01T09:58:24'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-07-01T09:58:24'),
        ),
    ]
