# Generated by Django 4.2.13 on 2024-07-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0007_depositfunds_created_by_depositfunds_trx_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositfunds',
            name='financialtransactionid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-07-01T10:14:51'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-07-01T10:14:51'),
        ),
    ]
