# Generated by Django 4.2.13 on 2024-07-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0008_depositfunds_financialtransactionid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('till_id', models.IntegerField(max_length=5)),
                ('till_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-07-01T15:03:36'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-07-01T15:03:36'),
        ),
        migrations.AddField(
            model_name='ecwuser',
            name='till',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecw.till'),
        ),
    ]
