# Generated by Django 4.2.13 on 2024-06-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0008_alter_depositfunds_banktransactionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-22T12:30:34'),
        ),
        migrations.AlterField(
            model_name='paymentinstructionrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
