# Generated by Django 4.2.13 on 2024-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0009_alter_depositfunds_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-24T09:34:46'),
        ),
    ]
