# Generated by Django 4.2.13 on 2024-07-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0009_till_alter_applogs_logtimestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-07-01T15:04:13'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-07-01T15:04:13'),
        ),
        migrations.AlterField(
            model_name='till',
            name='till_id',
            field=models.IntegerField(),
        ),
    ]
