# Generated by Django 4.2.13 on 2024-06-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0010_alter_depositfunds_transactiontimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
                ('headers', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('logtimestamp', models.DateTimeField(default='2024-06-25T12:31:43')),
            ],
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-25T12:31:43'),
        ),
    ]
