# Generated by Django 4.2.13 on 2024-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecw', '0011_applogs_alter_depositfunds_transactiontimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogs',
            name='logtimestamp',
            field=models.DateTimeField(default='2024-06-25T12:44:53'),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='bankcode',
            field=models.CharField(default='FTBLUGKA', max_length=30),
        ),
        migrations.AlterField(
            model_name='depositfunds',
            name='transactiontimestamp',
            field=models.DateTimeField(default='2024-06-25T12:44:53'),
        ),
    ]
